### ISSUE TITLE
Unhandled exception in /heroparam/batch

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#293]
After adding the new HeroParam endpoint in #285:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at DragaliaAPI.Services.Photon.HeroParamService.MapBonuses(DbDetailedPartyUnit unit, FortBonusList fortBonusList, HeroParam result) in /src/DragaliaAPI/Services/Photon/HeroParamService.cs:line 224
   at DragaliaAPI.Services.Photon.HeroParamService.MapHeroParam(DbDetailedPartyUnit unit, FortBonusList fortBonusList) in /src/DragaliaAPI/Services/Photon/HeroParamService.cs:line 183
```

RequestId: 0HMRO41C9FF1K:000003F3
AccountId: yS9GrxMH5SRzsrZM
ViewerId: 1269
PartySlot: 8

The log appears after user impersionation has ended for the above details, but probably because the .Select() is not evaluated until the item is added to the list and the HeroParamService scope is left.

The likely cause is one of the .First() calls in MapBonuses, but it is unclear why a call such as

```csharp
AtgenParamBonus paramBonus = fortBonusList.param_bonus.First(
    x => x.weapon_type == charaData.WeaponType
);
```

would throw. The bonus list should contain all bonuses for all weapon types / elements, and is not imported with the save. Moreover, `charaData` here is a MasterAsset model and so should have a standard WeaponType.

---

Party from save:
```json
{
    "party_no": 8,
    "party_name": "Lv. Up Team",
    "party_setting_list": [
        {
            "unit_no": 1,
            "chara_id": 10250303,
            "equip_weapon_key_id": 0,
            "equip_dragon_key_id": 665248,
            "equip_amulet_key_id": 0,
            "equip_amulet_2_key_id": 0,
            "equip_skin_weapon_id": 0,
            "equip_weapon_body_id": 30260301,
            "equip_weapon_skin_id": 30240202,
            "equip_crest_slot_type_1_crest_id_1": 40050137,
            "equip_crest_slot_type_1_crest_id_2": 40050128,
            "equip_crest_slot_type_1_crest_id_3": 40050098,
            "equip_crest_slot_type_2_crest_id_1": 40040100,
            "equip_crest_slot_type_2_crest_id_2": 40040003,
            "equip_crest_slot_type_3_crest_id_1": 40090019,
            "equip_crest_slot_type_3_crest_id_2": 40090002,
            "equip_talisman_key_id": 313601,
            "edit_skill_1_chara_id": 0,
            "edit_skill_2_chara_id": 10350303
        },
        {
            "unit_no": 2,
            "chara_id": 10740302,
            "equip_weapon_key_id": 0,
            "equip_dragon_key_id": 0,
            "equip_amulet_key_id": 0,
            "equip_amulet_2_key_id": 0,
            "equip_skin_weapon_id": 0,
            "equip_weapon_body_id": 0,
            "equip_weapon_skin_id": 0,
            "equip_crest_slot_type_1_crest_id_1": 0,
            "equip_crest_slot_type_1_crest_id_2": 0,
            "equip_crest_slot_type_1_crest_id_3": 0,
            "equip_crest_slot_type_2_crest_id_1": 0,
            "equip_crest_slot_type_2_crest_id_2": 0,
            "equip_crest_slot_type_3_crest_id_1": 0,
            "equip_crest_slot_type_3_crest_id_2": 0,
            "equip_talisman_key_id": 0,
            "edit_skill_1_chara_id": 10840501,
            "edit_skill_2_chara_id": 10440301
        },
        {
            "unit_no": 3,
            "chara_id": 10350303,
            "equip_weapon_key_id": 0,
            "equip_dragon_key_id": 0,
            "equip_amulet_key_id": 0,
            "equip_amulet_2_key_id": 0,
            "equip_skin_weapon_id": 0,
            "equip_weapon_body_id": 0,
            "equip_weapon_skin_id": 0,
            "equip_crest_slot_type_1_crest_id_1": 0,
            "equip_crest_slot_type_1_crest_id_2": 0,
            "equip_crest_slot_type_1_crest_id_3": 0,
            "equip_crest_slot_type_2_crest_id_1": 0,
            "equip_crest_slot_type_2_crest_id_2": 0,
            "equip_crest_slot_type_3_crest_id_1": 0,
            "equip_crest_slot_type_3_crest_id_2": 0,
            "equip_talisman_key_id": 0,
            "edit_skill_1_chara_id": 10840501,
            "edit_skill_2_chara_id": 10440301
        },
        {
            "unit_no": 4,
            "chara_id": 10150304,
            "equip_weapon_key_id": 0,
            "equip_dragon_key_id": 0,
            "equip_amulet_key_id": 0,
            "equip_amulet_2_key_id": 0,
            "equip_skin_weapon_id": 0,
            "equip_weapon_body_id": 0,
            "equip_weapon_skin_id": 0,
            "equip_crest_slot_type_1_crest_id_1": 0,
            "equip_crest_slot_type_1_crest_id_2": 0,
            "equip_crest_slot_type_1_crest_id_3": 0,
            "equip_crest_slot_type_2_crest_id_1": 0,
            "equip_crest_slot_type_2_crest_id_2": 0,
            "equip_crest_slot_type_3_crest_id_1": 0,
            "equip_crest_slot_type_3_crest_id_2": 0,
            "equip_talisman_key_id": 0,
            "edit_skill_1_chara_id": 10840501,
            "edit_skill_2_chara_id": 10440301
        }
    ]
},
```

**Comment by SapiensAnatis** [comment]
It wasn't that viewer id, sinkarth was using a battle royale character
