### ISSUE TITLE
Save import fails on first login

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#668]
**Describe the bug**
When you log in for the first time ever and have a save to import, the save import fails with

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at DragaliaAPI.Services.Game.SavefileService.Import(LoadIndexData savefile) in /src/DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs:line 209
   at DragaliaAPI.Services.Game.SavefileService.Import(LoadIndexData savefile) in /src/DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs:line 432
   at DragaliaAPI.Services.Game.SavefileService.ThreadSafeImport(LoadIndexData savefile) in /src/DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs:line 92
   at DragaliaAPI.Services.Game.SavefileService.ThreadSafeImport(LoadIndexData savefile) in /src/DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs:line 99
   at DragaliaAPI.Services.Game.AuthService.ImportSave(String idToken) in /src/DragaliaAPI/DragaliaAPI/Services/Game/AuthService.cs:line 142
```

Generally you then get sent to the tutorial.

**Expected behavior**
Even if you had no account previously, the save should import and enable you to skip the tutorial.

**Additional context**
Most likely this case needs special logic to avoid creating a new account?

**Comment by SapiensAnatis** [comment]
Doesn't appear to have re-occurred since PR, closing
